version: '1'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: smartface
      POSTGRES_USER: smartface
      POSTGRES_PASSWORD: password
    networks:
      - local


  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    command: start-dev
    links:
      - postgres
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN : admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: smartface
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: smartface
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://smartface:5432/keycloak
      PROXY_ADDRESS_FORWARDING: 'true'
      KC_PROXY: edge
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT_HTTPS: 'true'
    networks:
      - local

  # Kafka
  zookeeper:
    restart: always
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    depends_on:
      - "zookeeper"
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://kafka:9094
      KAFKA_CFG_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  local:
