# Keycloak Configuration
keycloak:
  auth-server-url: http://localhost:8080
  realm: smartface
  domain:  http://localhost:8080
  resource: smart-face-client
  credentials:
      secret: Fl4cSpdq5tseDykByzKZQNSR3xvvmE5X
  public-client: true
  ssl-required: none
  bearer-only: true
  use-resource-role-mappings: true

# Kafka Configuration
spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      auto-startup: false

#  retry:
#    enabled: true
#    max-attempts: 5
#    backoff:
#      delay: 5000
#      max-delay: 30000
#      multiplier: 2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    dialect: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/smartface

server:
  port: 8081