# Keycloak Configuration
keycloak:
  auth-server-url: http://localhost:8080 # Keycloak URL
  realm: smartface
  domain:  http://localhost:8080
  resource: admin-cli
  credentials:
      secret: Fl4cSpdq5tseDykByzKZQNSR3xvvmE5X
  public-client: true
  ssl-required: none
  bearer-only: true
  use-resource-role-mappings: true

# Kafka Configuration

# Spring Retry Configuration
# Database Configuration for Event Storage (optional for failure recovery)
spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      auto-startup: false
    producer:
      bootstrap-servers: <kafka-server>
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      acks: all
  retry:
    enabled: true
    max-attempts: 5
    backoff:
      delay: 5000
      max-delay: 30000
      multiplier: 2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    dialect: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/smartface

server:
  port: 8081